# DO NOT DELETE

calendar.o: ../../lib/c/include/stdio.h ../../lib/c/include/sys/types.h
calendar.o: ../../lib/c/include/libarch/types.h
calendar.o: ../../lib/c/include/libarch/common.h ../../lib/c/include/stdarg.h
calendar.o: ../../lib/c/include/str.h ../../lib/c/include/mem.h
calendar.o: ../../lib/c/include/stdbool.h ../../lib/c/include/abi/bool.h
calendar.o: ../../lib/c/include/io/verify.h ../../lib/c/include/abi/klog.h
