/***************************************
 * AUTO-GENERATED FILE, DO NOT EDIT!!! *
 * Generated by: tools/mkarray.py      *
 ***************************************/

#ifndef COMPOSITOR_IMAGES_H_
#define COMPOSITOR_IMAGES_H_

#include <sys/types.h>

extern uint8_t w2_tga[];
extern size_t w2_tga_size;

#endif
